### ISSUE TITLE
Support encoding when importing R source files

### ISSUE THREAD

**Issue by psychelzh** [rticulate/import#51] opened 2020-12-25 04:17 UTC
Currently, there is no option to set encoding of the importing file. This is very useful on Windows platform.

**Comment by torfason** [comment] 2021-01-05 14:45
International characters are very important (I rely on the Icealndic characters þ,æ,ð,ö and others myself). In general I feel that utf8 should be the solution (i.e. all source files and text in utf8, rather than setting encoding). However, I understand that there might be issues with that approach.

A few questions related to this:

- Is it the case that a script with international characters encoded in utf8 is not correctly imported?
- If yes to the above, is there a reason it not possible to save the script in utf8?
- if no to the above, I wonder if the value of getOption("encoding") is respected? 

The underlying function that import uses is `sys.source()`, which does not have an encoding parameter, so if the answers to the above questions are not „good“ then the fix might be difficult. It seems that a discussion about the `testthat` package from a few years back is focused on a very similar issue, is there something there that might help (https://github.com/r-lib/testthat/issues/28)?

**Comment by torfason** [comment] 2022-01-11 10:37
To the extent that the issue is a request for support of non-utf8 source files, I'm marking this as `wontfix`.

**Comment by torfason** [comment] 2022-05-16 11:58
Closing as `wontfix`. Feel free to reopen based on the answers to the points mentioned above, that is:

> * Is it the case that a script with international characters encoded in utf8 is not correctly imported?
> * If yes to the above, is there a reason it not possible to save the script in utf8?
> * if no to the above, I wonder if the value of getOption("encoding") is respected?

**Closed by torfason** 2022-05-16 11:58 UTC
Labels: wontfix
